/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrayTagCell: typeof import('./src/components/ArrayTagCell.vue')['default']
    BattleLogEntry: typeof import('./src/components/battle/BattleLogEntry.vue')['default']
    BattleLogPanel: typeof import('./src/components/battle/BattleLogPanel.vue')['default']
    BattleStatus: typeof import('./src/components/battle/BattleStatus.vue')['default']
    BattleView: typeof import('./src/components/battle/BattleView.vue')['default']
    DamageDisplay: typeof import('./src/components/battle/DamageDisplay.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElementIcon: typeof import('./src/components/battle/ElementIcon.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EnhancedArrayEditor: typeof import('./src/components/EnhancedArrayEditor.vue')['default']
    HealthRageBar: typeof import('./src/components/battle/HealthRageBar.vue')['default']
    Mark: typeof import('./src/components/battle/Mark.vue')['default']
    OptionalFieldEditor: typeof import('./src/components/OptionalFieldEditor.vue')['default']
    Pet: typeof import('./src/components/battle/Pet.vue')['default']
    PetButton: typeof import('./src/components/battle/PetButton.vue')['default']
    PetCard: typeof import('./src/components/petCard.vue')['default']
    PetIcon: typeof import('./src/components/PetIcon.vue')['default']
    PetSprite: typeof import('./src/components/battle/PetSprite.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillButton: typeof import('./src/components/battle/SkillButton.vue')['default']
    SpeciesSkillEditor: typeof import('./src/components/SpeciesSkillEditor.vue')['default']
    StorageManager: typeof import('./src/components/StorageManager.vue')['default']
    Tooltip: typeof import('./src/components/battle/Tooltip.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
