/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrayTagCell: typeof import('./src/components/ArrayTagCell.vue')['default']
    BattleLogEntry: typeof import('./src/components/BattleLogEntry.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTag: typeof import('element-plus/es')['ElTag']
    EnhancedArrayEditor: typeof import('./src/components/EnhancedArrayEditor.vue')['default']
    OptionalFieldEditor: typeof import('./src/components/OptionalFieldEditor.vue')['default']
    PetCard: typeof import('./src/components/petCard.vue')['default']
    PetStatus: typeof import('./src/components/PetStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeciesSkillEditor: typeof import('./src/components/SpeciesSkillEditor.vue')['default']
    StorageManager: typeof import('./src/components/StorageManager.vue')['default']
  }
}
