import type { BattleMessage, BattleState, PlayerSelection, PlayerTimerState, TimerConfig, Events, playerId } from '@arcadia-eternity/const';
import type { IBattleSystem, BattleRuntimeSnapshot, BattlePhaseExecutionEvent } from '@arcadia-eternity/interface';
import type { BattleInstance } from './game.js';
import type { MessageViewOptions } from './systems/message-bridge.js';
export declare class LocalBattleSystemV2 implements IBattleSystem {
    private battle;
    private static readonly RUNTIME_SNAPSHOT_FORMAT;
    private static readonly RUNTIME_SNAPSHOT_VERSION;
    private orchestrator;
    private selectionSystem;
    private messageBridge;
    private timerSystem;
    private battlePromise;
    private resumeFromSnapshot;
    private phaseEventSubscribers;
    private removePhaseExecutionObserver;
    constructor(battle: BattleInstance);
    get world(): import("@arcadia-eternity/engine").World;
    ready(): Promise<void>;
    getState(playerId?: playerId, showHidden?: boolean): Promise<BattleState>;
    getAvailableSelection(playerId: playerId): Promise<PlayerSelection[]>;
    submitAction(selection: PlayerSelection): Promise<void>;
    BattleEvent(callback: (message: BattleMessage) => void, options?: MessageViewOptions): () => void;
    isTimerEnabled(): Promise<boolean>;
    getPlayerTimerState(playerId: playerId): Promise<PlayerTimerState | null>;
    getAllPlayerTimerStates(): Promise<PlayerTimerState[]>;
    getTimerConfig(): Promise<TimerConfig>;
    startAnimation(source: string, expectedDuration: number, ownerId: playerId): Promise<string>;
    endAnimation(animationId: string, actualDuration?: number): Promise<void>;
    startReconnectGraceTimer(playerId: playerId, durationSec: number): Promise<void>;
    cancelReconnectGraceTimer(playerId: playerId): Promise<void>;
    onTimerEvent<K extends keyof Events>(eventType: K, handler: (data: Events[K]) => void): () => void;
    offTimerEvent<K extends keyof Events>(eventType: K, handler: (data: Events[K]) => void): void;
    onPhaseExecutionEvent(handler: (event: BattlePhaseExecutionEvent) => void | Promise<void>): () => void;
    setDevPetHp(petId: string, hp: number): void;
    setDevPlayerRage(playerId: string, rage: number): void;
    forceAISelection(selection: PlayerSelection): void;
    getAvailableActionsForPlayer(playerId: string): PlayerSelection[];
    createRuntimeSnapshot(): Promise<BattleRuntimeSnapshot>;
    restoreRuntimeSnapshot(snapshot: BattleRuntimeSnapshot): Promise<void>;
    cleanup(): Promise<void>;
    private initializeTimerPlayers;
    private handleReconnectGraceTimeout;
}
//# sourceMappingURL=local-battle.d.ts.map