export enum Type {
  Normal = 'Normal',
  Grass = 'Grass',
  Water = 'Water',
  Fire = 'Fire',
  Wind = 'Wind',
  Bug = 'Bug',
  Flying = 'Flying',
  Electric = 'Electric',
  Ground = 'Ground',
  Ice = 'Ice',
  Psychic = 'Psychic',
  Fighting = 'Fighting',
  Trait = 'Trait',
  Light = 'Light',
  Mystery = 'Mystery',
  Shadow = 'Shadow',
  Dragon = 'Dragon',
  Desert = 'Desert',
  Ancient = 'Ancient',
  Divine = 'Divine',
  Miracle = 'Miracle',
  Holy = 'Holy',
  ElfKing = 'ElfKing',
}

export const TYPE_MAP: { [key: string]: { name: string; emoji: string } } = {
  Normal: { name: '普通', emoji: '⚪' },
  Grass: { name: '草', emoji: '🌱' },
  Water: { name: '水', emoji: '💧' },
  Fire: { name: '火', emoji: '🔥' },
  Wind: { name: '风', emoji: '🌬️' },
  Bug: { name: '虫', emoji: '🐛' },
  Flying: { name: '飞行', emoji: '🕊️' },
  Electric: { name: '电', emoji: '⚡' },
  Ground: { name: '地面', emoji: '🌍' },
  Ice: { name: '冰', emoji: '❄️' },
  Psychic: { name: '超能', emoji: '🧠' },
  Fighting: { name: '战斗', emoji: '🥋' },
  Trait: { name: '特质', emoji: '✨' },
  Light: { name: '光', emoji: '💡' },
  Mystery: { name: '神秘', emoji: '🌀' },
  Shadow: { name: '暗影', emoji: '🌑' },
  Dragon: { name: '龙', emoji: '🐉' },
  Desert: { name: '沙漠', emoji: '🏜️' },
  Ancient: { name: '上古', emoji: '🗿' },
  Divine: { name: '神遁', emoji: '🙏' },
  Miracle: { name: '神迹', emoji: '🌟' },
  Holy: { name: '圣灵', emoji: '👼' },
  ElfKing: { name: '精灵王', emoji: '🧝‍♂️' },
}

export const TYPE_CHART: Record<Type, Record<Type, number>> = {
  [Type.Normal]: {
    [Type.Normal]: 1,
    [Type.Grass]: 1,
    [Type.Water]: 1,
    [Type.Fire]: 1,
    [Type.Wind]: 1,
    [Type.Bug]: 1,
    [Type.Flying]: 1,
    [Type.Electric]: 1,
    [Type.Ground]: 1,
    [Type.Ice]: 1,
    [Type.Psychic]: 1,
    [Type.Fighting]: 1,
    [Type.Trait]: 1,
    [Type.Light]: 1,
    [Type.Mystery]: 1,
    [Type.Shadow]: 1,
    [Type.Dragon]: 1,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Grass]: {
    [Type.Normal]: 1,
    [Type.Grass]: 0.5,
    [Type.Water]: 2,
    [Type.Fire]: 0.5,
    [Type.Wind]: 1,
    [Type.Bug]: 0.5,
    [Type.Flying]: 0.5,
    [Type.Electric]: 1,
    [Type.Ground]: 1,
    [Type.Ice]: 0.5,
    [Type.Psychic]: 1,
    [Type.Fighting]: 1,
    [Type.Trait]: 0.5,
    [Type.Light]: 2,
    [Type.Mystery]: 1,
    [Type.Shadow]: 1,
    [Type.Dragon]: 1,
    [Type.Desert]: 2,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Water]: {
    [Type.Normal]: 1,
    [Type.Grass]: 0.5,
    [Type.Water]: 0.5,
    [Type.Fire]: 2,
    [Type.Wind]: 1,
    [Type.Bug]: 1,
    [Type.Flying]: 1,
    [Type.Electric]: 1,
    [Type.Ground]: 2,
    [Type.Ice]: 1,
    [Type.Psychic]: 1,
    [Type.Fighting]: 1,
    [Type.Trait]: 0.5,
    [Type.Light]: 1,
    [Type.Mystery]: 0.5,
    [Type.Shadow]: 2,
    [Type.Dragon]: 1,
    [Type.Desert]: 0.5,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Fire]: {
    [Type.Normal]: 1,
    [Type.Grass]: 2,
    [Type.Water]: 0.5,
    [Type.Fire]: 0.5,
    [Type.Wind]: 2,
    [Type.Bug]: 2,
    [Type.Flying]: 1,
    [Type.Electric]: 1,
    [Type.Ground]: 1,
    [Type.Ice]: 2,
    [Type.Psychic]: 1,
    [Type.Fighting]: 0.5,
    [Type.Trait]: 0.5,
    [Type.Light]: 1,
    [Type.Mystery]: 1,
    [Type.Shadow]: 1,
    [Type.Dragon]: 0.5,
    [Type.Desert]: 0.5,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Wind]: {
    [Type.Normal]: 1,
    [Type.Grass]: 1,
    [Type.Water]: 1,
    [Type.Fire]: 1,
    [Type.Wind]: 0.5,
    [Type.Bug]: 1,
    [Type.Flying]: 0.5,
    [Type.Electric]: 1,
    [Type.Ground]: 2,
    [Type.Ice]: 0,
    [Type.Psychic]: 1,
    [Type.Fighting]: 2,
    [Type.Trait]: 0.5,
    [Type.Light]: 1,
    [Type.Mystery]: 0.5,
    [Type.Shadow]: 1,
    [Type.Dragon]: 0.5,
    [Type.Desert]: 2,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Bug]: {
    [Type.Normal]: 1,
    [Type.Grass]: 2,
    [Type.Water]: 1,
    [Type.Fire]: 0.5,
    [Type.Wind]: 1,
    [Type.Bug]: 1,
    [Type.Flying]: 0.5,
    [Type.Electric]: 1,
    [Type.Ground]: 1,
    [Type.Ice]: 0.5,
    [Type.Psychic]: 2,
    [Type.Fighting]: 0.5,
    [Type.Trait]: 2,
    [Type.Light]: 1,
    [Type.Mystery]: 1,
    [Type.Shadow]: 0.5,
    [Type.Dragon]: 2,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Flying]: {
    [Type.Normal]: 1,
    [Type.Grass]: 2,
    [Type.Water]: 1,
    [Type.Fire]: 1,
    [Type.Wind]: 0.5,
    [Type.Bug]: 2,
    [Type.Flying]: 1,
    [Type.Electric]: 0.5,
    [Type.Ground]: 2,
    [Type.Ice]: 1,
    [Type.Psychic]: 1,
    [Type.Fighting]: 1,
    [Type.Trait]: 0.5,
    [Type.Light]: 0.5,
    [Type.Mystery]: 1,
    [Type.Shadow]: 0.5,
    [Type.Dragon]: 0.5,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Electric]: {
    [Type.Normal]: 1,
    [Type.Grass]: 0.5,
    [Type.Water]: 2,
    [Type.Fire]: 1,
    [Type.Wind]: 0.5,
    [Type.Bug]: 1,
    [Type.Flying]: 2,
    [Type.Electric]: 0.5,
    [Type.Ground]: 0,
    [Type.Ice]: 1,
    [Type.Psychic]: 1,
    [Type.Fighting]: 1,
    [Type.Trait]: 0.5,
    [Type.Light]: 1,
    [Type.Mystery]: 0.5,
    [Type.Shadow]: 2,
    [Type.Dragon]: 1,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Ground]: {
    [Type.Normal]: 1,
    [Type.Grass]: 0.5,
    [Type.Water]: 1,
    [Type.Fire]: 2,
    [Type.Wind]: 0.5,
    [Type.Bug]: 1,
    [Type.Flying]: 0,
    [Type.Electric]: 2,
    [Type.Ground]: 1,
    [Type.Ice]: 1,
    [Type.Psychic]: 0.5,
    [Type.Fighting]: 1,
    [Type.Trait]: 2,
    [Type.Light]: 2,
    [Type.Mystery]: 0.5,
    [Type.Shadow]: 0.5,
    [Type.Dragon]: 0.5,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Ice]: {
    [Type.Normal]: 1,
    [Type.Grass]: 1,
    [Type.Water]: 0.5,
    [Type.Fire]: 0.5,
    [Type.Wind]: 2,
    [Type.Bug]: 0.5,
    [Type.Flying]: 2,
    [Type.Electric]: 1,
    [Type.Ground]: 1,
    [Type.Ice]: 0.5,
    [Type.Psychic]: 1,
    [Type.Fighting]: 0.5,
    [Type.Trait]: 0.5,
    [Type.Light]: 1,
    [Type.Mystery]: 1,
    [Type.Shadow]: 1,
    [Type.Dragon]: 1,
    [Type.Desert]: 2,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Psychic]: {
    [Type.Normal]: 1,
    [Type.Grass]: 1,
    [Type.Water]: 1,
    [Type.Fire]: 1,
    [Type.Wind]: 2,
    [Type.Bug]: 0.5,
    [Type.Flying]: 1,
    [Type.Electric]: 0.5,
    [Type.Ground]: 0.5,
    [Type.Ice]: 1,
    [Type.Psychic]: 0.5,
    [Type.Fighting]: 2,
    [Type.Trait]: 0.5,
    [Type.Light]: 0.5,
    [Type.Mystery]: 2,
    [Type.Shadow]: 1,
    [Type.Dragon]: 1,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Fighting]: {
    [Type.Normal]: 1,
    [Type.Grass]: 1,
    [Type.Water]: 0.5,
    [Type.Fire]: 1,
    [Type.Wind]: 0.5,
    [Type.Bug]: 2,
    [Type.Flying]: 1,
    [Type.Electric]: 1,
    [Type.Ground]: 1,
    [Type.Ice]: 2,
    [Type.Psychic]: 0.5,
    [Type.Fighting]: 0.5,
    [Type.Trait]: 0.5,
    [Type.Light]: 1,
    [Type.Mystery]: 1,
    [Type.Shadow]: 1,
    [Type.Dragon]: 2,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Trait]: {
    [Type.Normal]: 1,
    [Type.Grass]: 0.5,
    [Type.Water]: 0.5,
    [Type.Fire]: 0.5,
    [Type.Wind]: 0.5,
    [Type.Bug]: 2,
    [Type.Flying]: 0.5,
    [Type.Electric]: 0.5,
    [Type.Ground]: 2,
    [Type.Ice]: 0.5,
    [Type.Psychic]: 0.5,
    [Type.Fighting]: 0.5,
    [Type.Trait]: 0.5,
    [Type.Light]: 2,
    [Type.Mystery]: 0.5,
    [Type.Shadow]: 2,
    [Type.Dragon]: 2,
    [Type.Desert]: 2,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Light]: {
    [Type.Normal]: 1,
    [Type.Grass]: 0,
    [Type.Water]: 1,
    [Type.Fire]: 1,
    [Type.Wind]: 1,
    [Type.Bug]: 0.5,
    [Type.Flying]: 1,
    [Type.Electric]: 1,
    [Type.Ground]: 1,
    [Type.Ice]: 0.5,
    [Type.Psychic]: 2,
    [Type.Fighting]: 1,
    [Type.Trait]: 2,
    [Type.Light]: 0.5,
    [Type.Mystery]: 2,
    [Type.Shadow]: 2,
    [Type.Dragon]: 1,
    [Type.Desert]: 0.5,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Mystery]: {
    [Type.Normal]: 1,
    [Type.Grass]: 1,
    [Type.Water]: 1,
    [Type.Fire]: 1,
    [Type.Wind]: 1,
    [Type.Bug]: 2,
    [Type.Flying]: 2,
    [Type.Electric]: 1,
    [Type.Ground]: 0.5,
    [Type.Ice]: 1,
    [Type.Psychic]: 1,
    [Type.Fighting]: 0.5,
    [Type.Trait]: 0.5,
    [Type.Light]: 1,
    [Type.Mystery]: 0.5,
    [Type.Shadow]: 1,
    [Type.Dragon]: 0.5,
    [Type.Desert]: 2,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Shadow]: {
    [Type.Normal]: 1,
    [Type.Grass]: 1,
    [Type.Water]: 0.5,
    [Type.Fire]: 1,
    [Type.Wind]: 1,
    [Type.Bug]: 0.5,
    [Type.Flying]: 1,
    [Type.Electric]: 1,
    [Type.Ground]: 0.5,
    [Type.Ice]: 1,
    [Type.Psychic]: 2,
    [Type.Fighting]: 1,
    [Type.Trait]: 2,
    [Type.Light]: 0.5,
    [Type.Mystery]: 1,
    [Type.Shadow]: 2,
    [Type.Dragon]: 2,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Dragon]: {
    [Type.Normal]: 1,
    [Type.Grass]: 1,
    [Type.Water]: 2,
    [Type.Fire]: 1,
    [Type.Wind]: 1,
    [Type.Bug]: 1,
    [Type.Flying]: 0.5,
    [Type.Electric]: 0.5,
    [Type.Ground]: 1,
    [Type.Ice]: 2,
    [Type.Psychic]: 0.5,
    [Type.Fighting]: 1,
    [Type.Trait]: 2,
    [Type.Light]: 1,
    [Type.Mystery]: 2,
    [Type.Shadow]: 0.5,
    [Type.Dragon]: 1,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Desert]: {
    [Type.Normal]: 1,
    [Type.Grass]: 0.5,
    [Type.Water]: 1,
    [Type.Fire]: 2,
    [Type.Wind]: 0.5,
    [Type.Bug]: 1,
    [Type.Flying]: 0.5,
    [Type.Electric]: 2,
    [Type.Ground]: 1,
    [Type.Ice]: 0.5,
    [Type.Psychic]: 1,
    [Type.Fighting]: 1,
    [Type.Trait]: 2,
    [Type.Light]: 1,
    [Type.Mystery]: 0.5,
    [Type.Shadow]: 1,
    [Type.Dragon]: 1,
    [Type.Desert]: 0.5,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Ancient]: {
    [Type.Normal]: 1,
    [Type.Grass]: 1,
    [Type.Water]: 1,
    [Type.Fire]: 1,
    [Type.Wind]: 1,
    [Type.Bug]: 1,
    [Type.Flying]: 1,
    [Type.Electric]: 1,
    [Type.Ground]: 1,
    [Type.Ice]: 1,
    [Type.Psychic]: 1,
    [Type.Fighting]: 1,
    [Type.Trait]: 1,
    [Type.Light]: 1,
    [Type.Mystery]: 1,
    [Type.Shadow]: 1,
    [Type.Dragon]: 1,
    [Type.Desert]: 1,
    [Type.Ancient]: 0.5,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.75,
  },
  [Type.Divine]: {
    [Type.Normal]: 0.75,
    [Type.Grass]: 0.75,
    [Type.Water]: 0.75,
    [Type.Fire]: 0.75,
    [Type.Wind]: 0.75,
    [Type.Bug]: 0.75,
    [Type.Flying]: 0.75,
    [Type.Electric]: 0.75,
    [Type.Ground]: 0.75,
    [Type.Ice]: 0.75,
    [Type.Psychic]: 0.75,
    [Type.Fighting]: 0.75,
    [Type.Trait]: 0.75,
    [Type.Light]: 0.75,
    [Type.Mystery]: 0.75,
    [Type.Shadow]: 0.75,
    [Type.Dragon]: 0.75,
    [Type.Desert]: 0.75,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 0.75,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 0.75,
    [Type.ElfKing]: 0.75,
  },
  [Type.Miracle]: {
    [Type.Normal]: 2,
    [Type.Grass]: 2,
    [Type.Water]: 2,
    [Type.Fire]: 2,
    [Type.Wind]: 2,
    [Type.Bug]: 2,
    [Type.Flying]: 2,
    [Type.Electric]: 2,
    [Type.Ground]: 2,
    [Type.Ice]: 2,
    [Type.Psychic]: 2,
    [Type.Fighting]: 2,
    [Type.Trait]: 2,
    [Type.Light]: 2,
    [Type.Mystery]: 2,
    [Type.Shadow]: 2,
    [Type.Dragon]: 2,
    [Type.Desert]: 2,
    [Type.Ancient]: 0.75,
    [Type.Divine]: 1,
    [Type.Miracle]: 0.75,
    [Type.Holy]: 2,
    [Type.ElfKing]: 1,
  },
  [Type.Holy]: {
    [Type.Normal]: 1.25,
    [Type.Grass]: 1.25,
    [Type.Water]: 1.25,
    [Type.Fire]: 1.25,
    [Type.Wind]: 1.25,
    [Type.Bug]: 1.25,
    [Type.Flying]: 1.25,
    [Type.Electric]: 1.25,
    [Type.Ground]: 1.25,
    [Type.Ice]: 1.25,
    [Type.Psychic]: 1.25,
    [Type.Fighting]: 1.25,
    [Type.Trait]: 1.25,
    [Type.Light]: 1.25,
    [Type.Mystery]: 1.25,
    [Type.Shadow]: 1.25,
    [Type.Dragon]: 1.25,
    [Type.Desert]: 1.25,
    [Type.Ancient]: 1,
    [Type.Divine]: 0.5,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 1,
  },
  [Type.ElfKing]: {
    [Type.Normal]: 1.25,
    [Type.Grass]: 1.25,
    [Type.Water]: 1.25,
    [Type.Fire]: 1.25,
    [Type.Wind]: 1.25,
    [Type.Bug]: 1.25,
    [Type.Flying]: 1.25,
    [Type.Electric]: 1.25,
    [Type.Ground]: 1.25,
    [Type.Ice]: 1.25,
    [Type.Psychic]: 1.25,
    [Type.Fighting]: 1.25,
    [Type.Trait]: 1.25,
    [Type.Light]: 1.25,
    [Type.Mystery]: 1.25,
    [Type.Shadow]: 1.25,
    [Type.Dragon]: 1.25,
    [Type.Desert]: 1.25,
    [Type.Ancient]: 1,
    [Type.Divine]: 0.75,
    [Type.Miracle]: 1.25,
    [Type.Holy]: 1,
    [Type.ElfKing]: 0.5,
  },
}
