version: '3.8'

services:
  # Basic configuration without battle reports
  arcadia-eternity-basic:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8102:8102"
    environment:
      - NODE_ENV=production
      - PORT=8102
      - CORS_ORIGIN=http://localhost:3000,http://localhost:5173
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8102/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Full configuration with battle reports enabled
  arcadia-eternity-full:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8103:8102"
    environment:
      - NODE_ENV=production
      - PORT=8102
      - CORS_ORIGIN=http://localhost:3000,http://localhost:5173
      # Battle reports configuration
      - SUPABASE_URL=https://your-project.supabase.co
      - SUPABASE_ANON_KEY=your-anon-key
      - SUPABASE_SERVICE_KEY=your-service-key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8102/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Configuration using .env file
  arcadia-eternity-env:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8104:8102"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8102/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# Usage examples:
# 1. Run basic server without battle reports:
#    docker-compose -f docker-compose.example.yml up arcadia-eternity-basic
#
# 2. Run full server with battle reports:
#    docker-compose -f docker-compose.example.yml up arcadia-eternity-full
#
# 3. Run server using .env file configuration:
#    docker-compose -f docker-compose.example.yml up arcadia-eternity-env
