version: '3.8'

services:
  arcadia-eternity:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8102:8102"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8102/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    # Optional: limit resources
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
