# fly.toml app configuration file generated for test-battle on 2025-05-07T21:09:04+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-battle'
primary_region = 'hkg'

[build]
# Image will be specified dynamically during deployment via --image flag
# This ensures we always use the latest built image
# image = 'ghcr.io/arcadia-eternity/arcadia-eternity:main'

[http_service]
internal_port = 8102
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
max_machines_running = 5
processes = ['app']

# gRPC 服务配置 - 仅内部使用，不暴露端口
# gRPC 服务在内部网络中运行，不需要外部访问

# Health check configuration
[[services.http_checks]]
interval = '30s'
timeout = '10s'
grace_period = '30s'
method = 'GET'
path = '/health'

# Metrics endpoint for monitoring
[[services.http_checks]]
interval = '60s'
timeout = '15s'
grace_period = '30s'
method = 'GET'
path = '/metrics'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
# Email configuration
EMAIL_PROVIDER = "smtp"
SMTP_HOST = "smtp.qcloudmail.com"
SMTP_PROT = "465"
SMTP_SECURE = "true"
EMAIL_FROM = "noreply@auth.yuuinih.com"
EMAIL_FROM_NAME = "阿卡迪亚永恒"

# CORS configuration
CORS_ORIGIN = "https://battle.yuuinih.com,https://test-battle.netlify.app"

# Cluster configuration
CLUSTER_ENABLED = "true"
CLUSTER_INSTANCE_REGION = "hkg"
CLUSTER_HEARTBEAT_INTERVAL = "30000"
CLUSTER_HEALTH_CHECK_INTERVAL = "60000"
CLUSTER_FAILOVER_TIMEOUT = "120000"

# gRPC configuration for Fly.io
GRPC_PORT = "50051"
GRPC_BIND_ADDRESS = "0.0.0.0"
# Fly.io 内部网络发现
FLY_APP_NAME = "test-battle"
FLY_REGION = "hkg"

# Redis configuration (will be set via secrets)
# REDIS_HOST will be set via fly secrets
# REDIS_PASSWORD will be set via fly secrets
REDIS_PORT = "6379"
REDIS_DB = "0"
REDIS_KEY_PREFIX = "arcadia:"
REDIS_TLS = "true"
