import { TimeoutType, type Events, type PlayerTimerState, type TimerConfig } from '@arcadia-eternity/const';
import { type World } from '@arcadia-eternity/engine';
type DecisionWindowPhase = 'selection' | 'switch' | 'teamSelection';
type TimerTimeoutHandler = (playerId: string, timeoutType: TimeoutType) => Promise<string | undefined> | string | undefined;
type ReconnectTimeoutHandler = (playerId: string) => Promise<string | undefined> | string | undefined;
interface StartDecisionWindowOptions {
    phase: DecisionWindowPhase;
    playerIds: string[];
    turnTimeLimitOverrideSec?: number;
    onTimeout?: TimerTimeoutHandler;
}
export declare class TimerSystem {
    private world;
    private config;
    private readonly playerStates;
    private readonly animations;
    private readonly reconnectWindows;
    private activeWindow;
    private tickTimer;
    private tickInFlight;
    private reconnectTimeoutHandler?;
    private readonly handlers;
    constructor(world: World, config?: Partial<TimerConfig>);
    setWorld(world: World): void;
    initializePlayers(playerIds: string[]): void;
    isEnabled(): boolean;
    getConfig(): TimerConfig;
    setReconnectTimeoutHandler(handler: ReconnectTimeoutHandler | undefined): void;
    startReconnectGraceWindow(playerId: string, durationSec: number): Promise<void>;
    cancelReconnectGraceWindow(playerId: string): boolean;
    getPlayerState(playerId: string): PlayerTimerState | null;
    getAllPlayerStates(): PlayerTimerState[];
    on<K extends keyof Events>(eventType: K, handler: (data: Events[K]) => void): () => void;
    off<K extends keyof Events>(eventType: K, handler: (data: Events[K]) => void): void;
    startDecisionWindow(options: StartDecisionWindowOptions): Promise<void>;
    markPlayerResolved(playerId: string): void;
    stopDecisionWindow(): void;
    startAnimation(source: string, expectedDuration: number, ownerId: string): string;
    endAnimation(animationId: string, actualDuration?: number): void;
    cleanup(): void;
    private startTicking;
    private stopTicking;
    private refreshTickingState;
    private hasPendingTickWork;
    private handleTick;
    private handleDecisionWindowTick;
    private checkImmediateTimeouts;
    private checkImmediateReconnectTimeouts;
    private handleReconnectTick;
    private processReconnectTimeouts;
    private processTimeouts;
    private applySystemPauseFromResolution;
    private ensurePlayerState;
    private clearAnimation;
    private forceEndAnimation;
    private clearAnimations;
    private hasActiveAnimations;
    private isTurnTimeout;
    private isTotalTimeout;
    private emitSnapshots;
    private createPlayerSnapshot;
    private getEffectiveTurnTimeLimit;
    private toPublicTime;
    private emit;
    private persistState;
    private readPersistedState;
}
export {};
//# sourceMappingURL=timer.system.d.ts.map