import { type Static } from '@sinclair/typebox';
export declare const UseSkillContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"use-skill">;
    parentId: import("@sinclair/typebox").TString;
    petId: import("@sinclair/typebox").TString;
    skillId: import("@sinclair/typebox").TString;
    originPlayerId: import("@sinclair/typebox").TString;
    selectTarget: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    priority: import("@sinclair/typebox").TNumber;
    category: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    element: import("@sinclair/typebox").TString;
    power: import("@sinclair/typebox").TNumber;
    accuracy: import("@sinclair/typebox").TNumber;
    petAccuracy: import("@sinclair/typebox").TNumber;
    rage: import("@sinclair/typebox").TNumber;
    evasion: import("@sinclair/typebox").TNumber;
    critRate: import("@sinclair/typebox").TNumber;
    ignoreShield: import("@sinclair/typebox").TBoolean;
    ignoreStageStrategy: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    multihit: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TTuple<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TNumber]>, import("@sinclair/typebox").TNumber]>;
    available: import("@sinclair/typebox").TBoolean;
    actualTargetId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    hitResult: import("@sinclair/typebox").TBoolean;
    crit: import("@sinclair/typebox").TBoolean;
    multihitResult: import("@sinclair/typebox").TNumber;
    currentHitCount: import("@sinclair/typebox").TNumber;
    damageType: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    typeMultiplier: import("@sinclair/typebox").TNumber;
    stabMultiplier: import("@sinclair/typebox").TNumber;
    critMultiplier: import("@sinclair/typebox").TNumber;
    baseDamage: import("@sinclair/typebox").TNumber;
    randomFactor: import("@sinclair/typebox").TNumber;
    defeated: import("@sinclair/typebox").TBoolean;
}>;
export declare const DamageContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"damage">;
    parentId: import("@sinclair/typebox").TString;
    sourceId: import("@sinclair/typebox").TString;
    targetId: import("@sinclair/typebox").TString;
    baseDamage: import("@sinclair/typebox").TNumber;
    damageType: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    crit: import("@sinclair/typebox").TBoolean;
    effectiveness: import("@sinclair/typebox").TNumber;
    ignoreShield: import("@sinclair/typebox").TBoolean;
    randomFactor: import("@sinclair/typebox").TNumber;
    modified: import("@sinclair/typebox").TTuple<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TNumber]>;
    minThreshold: import("@sinclair/typebox").TNumber;
    maxThreshold: import("@sinclair/typebox").TNumber;
    damageResult: import("@sinclair/typebox").TNumber;
    available: import("@sinclair/typebox").TBoolean;
    element: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export declare const HealContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"heal">;
    parentId: import("@sinclair/typebox").TString;
    sourceId: import("@sinclair/typebox").TString;
    targetId: import("@sinclair/typebox").TString;
    baseHeal: import("@sinclair/typebox").TNumber;
    ignoreEffect: import("@sinclair/typebox").TBoolean;
    modified: import("@sinclair/typebox").TTuple<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TNumber]>;
    healResult: import("@sinclair/typebox").TNumber;
    available: import("@sinclair/typebox").TBoolean;
}>;
export declare const RageContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"rage">;
    parentId: import("@sinclair/typebox").TString;
    targetPlayerId: import("@sinclair/typebox").TString;
    reason: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    modifiedType: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    value: import("@sinclair/typebox").TNumber;
    ignoreRageObtainEfficiency: import("@sinclair/typebox").TBoolean;
    modified: import("@sinclair/typebox").TTuple<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TNumber]>;
    rageChangeResult: import("@sinclair/typebox").TNumber;
    available: import("@sinclair/typebox").TBoolean;
}>;
export declare const AddMarkContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"add-mark">;
    parentId: import("@sinclair/typebox").TString;
    targetId: import("@sinclair/typebox").TString;
    baseMarkId: import("@sinclair/typebox").TString;
    baseMark: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    stack: import("@sinclair/typebox").TNumber;
    duration: import("@sinclair/typebox").TNumber;
    config: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    configOverride: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TAny>;
    statLevelMarkLevel: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    creatorId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    available: import("@sinclair/typebox").TBoolean;
}>;
export declare const RemoveMarkContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"remove-mark">;
    parentId: import("@sinclair/typebox").TString;
    markId: import("@sinclair/typebox").TString;
    available: import("@sinclair/typebox").TBoolean;
}>;
export declare const SwitchPetContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"switch-pet">;
    parentId: import("@sinclair/typebox").TString;
    originPlayerId: import("@sinclair/typebox").TString;
    switchInPetId: import("@sinclair/typebox").TString;
    switchOutPetId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export declare const StackContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"stack">;
    parentId: import("@sinclair/typebox").TString;
    existingMarkId: import("@sinclair/typebox").TString;
    incomingMarkId: import("@sinclair/typebox").TString;
    stacksBefore: import("@sinclair/typebox").TNumber;
    durationBefore: import("@sinclair/typebox").TNumber;
    stacksAfter: import("@sinclair/typebox").TNumber;
    durationAfter: import("@sinclair/typebox").TNumber;
    stackStrategy: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    available: import("@sinclair/typebox").TBoolean;
}>;
export declare const ConsumeStackContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"consumeStack">;
    parentId: import("@sinclair/typebox").TString;
    markId: import("@sinclair/typebox").TString;
    requestedAmount: import("@sinclair/typebox").TNumber;
    actualAmount: import("@sinclair/typebox").TNumber;
    available: import("@sinclair/typebox").TBoolean;
}>;
export declare const TransformContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"transform">;
    parentId: import("@sinclair/typebox").TString;
    targetId: import("@sinclair/typebox").TString;
    targetType: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    fromBaseId: import("@sinclair/typebox").TString;
    toBaseId: import("@sinclair/typebox").TString;
    transformType: import("@sinclair/typebox").TUnion<import("@sinclair/typebox").TLiteral<string>[]>;
    priority: import("@sinclair/typebox").TNumber;
    causedById: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    available: import("@sinclair/typebox").TBoolean;
}>;
export declare const TurnContextSchema: import("@sinclair/typebox").TObject<{
    type: import("@sinclair/typebox").TLiteral<"turn">;
    parentId: import("@sinclair/typebox").TString;
    contextIds: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>;
}>;
export type UseSkillContextData = Static<typeof UseSkillContextSchema>;
export type DamageContextData = Static<typeof DamageContextSchema>;
export type HealContextData = Static<typeof HealContextSchema>;
export type RageContextData = Static<typeof RageContextSchema>;
export type AddMarkContextData = Static<typeof AddMarkContextSchema>;
export type RemoveMarkContextData = Static<typeof RemoveMarkContextSchema>;
export type SwitchPetContextData = Static<typeof SwitchPetContextSchema>;
export type StackContextData = Static<typeof StackContextSchema>;
export type ConsumeStackContextData = Static<typeof ConsumeStackContextSchema>;
export type TransformContextData = Static<typeof TransformContextSchema>;
export type TurnContextData = Static<typeof TurnContextSchema>;
//# sourceMappingURL=context.schema.d.ts.map