-- Wrap auth/session function calls in RLS policy predicates in (SELECT ...) so Postgres
-- evaluates them once per statement (InitPlan) instead of once per row -- the
-- Supabase-documented RLS perf pattern. Predicate-equivalent (row visibility unchanged).
-- Generated by 'pgrls fix --rule PERF001' and verified (PERF001 -> 0). Refs #195.

-- [PERF001] Wrap auth function call(s) in policy 'Anyone can view battle records or service can view any' on public.battle_records so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Anyone can view battle records or service can view any" ON public.battle_records
    USING (TRUE OR (SELECT auth.role()) = CAST('service_role' AS text) OR (SELECT auth.uid()) IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'Only service can update battle records' on public.battle_records so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Only service can update battle records" ON public.battle_records
    USING ((SELECT auth.role()) = CAST('service_role' AS text) OR (SELECT auth.uid()) IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'Anyone can view elo ratings or service can view any' on public.player_elo_ratings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Anyone can view elo ratings or service can view any" ON public.player_elo_ratings
    USING (TRUE OR (SELECT auth.role()) = CAST('service_role' AS text) OR (SELECT auth.uid()) IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'Only service can modify elo ratings' on public.player_elo_ratings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Only service can modify elo ratings" ON public.player_elo_ratings
    USING ((SELECT auth.role()) = CAST('service_role' AS text) OR (SELECT auth.uid()) IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'Anyone can view player stats or service can view any' on public.player_stats so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Anyone can view player stats or service can view any" ON public.player_stats
    USING (TRUE OR (SELECT auth.role()) = CAST('service_role' AS text) OR (SELECT auth.uid()) IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'Only service can modify stats' on public.player_stats so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Only service can modify stats" ON public.player_stats
    USING ((SELECT auth.role()) = CAST('service_role' AS text) OR (SELECT auth.uid()) IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'Players can update own record or service can update any' on public.players so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Players can update own record or service can update any" ON public.players
    USING (CAST((SELECT auth.uid()) AS text) = id OR (SELECT auth.role()) = CAST('service_role' AS text) OR (SELECT auth.uid()) IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'Players can view all records or service can view any' on public.players so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Players can view all records or service can view any" ON public.players
    USING (TRUE OR (SELECT auth.role()) = CAST('service_role' AS text) OR (SELECT auth.uid()) IS NULL);
