name: Deploy Development Environment

on:
  # 等待开发环境Docker镜像构建完成
  workflow_run:
    workflows: ['Build and Push Docker Image']
    types:
      - completed
    branches: [main, master]
  # 手动触发
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # 部署开发环境（等待Docker镜像构建完成）
  deploy-development:
    runs-on: ubuntu-latest
    # 只有当Docker构建成功时才运行
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
    steps:
      - name: Notify development deployment
        run: |
          echo "Development Docker image has been built successfully!"
          echo "Image is ready for deployment to development environment."
          echo ""
          echo "If you have a development server, you can deploy the image:"
          echo "docker run -p 8102:8102 ghcr.io/${{ github.repository }}:dev"
