name: Deploy to Fly.io (Production)

on:
  # 等待生产镜像构建完成后部署
  workflow_run:
    workflows: ['Build Production Docker Image']
    types:
      - completed
    branches:
      - main
  # 通过repository_dispatch触发部署
  repository_dispatch:
    types: [deploy-production]
  # 手动触发
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'
        type: choice
        options:
          - production
      version:
        description: 'Version to deploy'
        required: false
        type: string

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  deploy:
    name: Deploy to Fly.io (Production)
    runs-on: ubuntu-latest
    environment: production
    # 只有当Docker构建成功时才运行，或者手动触发，或者通过repository_dispatch触发
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' }}

    steps:
      - name: Debug workflow trigger
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow run name: ${{ github.event.workflow_run.name }}"
          echo "Workflow run head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow run head sha: ${{ github.event.workflow_run.head_sha }}"
          echo "Repository dispatch action: ${{ github.event.action }}"
          echo "Repository dispatch client payload: ${{ toJson(github.event.client_payload) }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version || github.event.workflow_run.head_sha || 'main' }}

      - name: Determine version
        id: version
        shell: bash
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          elif [ -n "${{ github.event.client_payload.version }}" ]; then
            VERSION="${{ github.event.client_payload.version }}"
          else
            # 从package.json读取版本号
            VERSION="$(node -p "require('./package.json').version")"
          fi
          # 移除v前缀（如果存在）
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Deploying production version: $VERSION"

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine production image reference
        id: image-info
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}"
          VERSION="${{ steps.version.outputs.version }}"

          if [ "$VERSION" = "latest" ]; then
            IMAGE_REF="${IMAGE_NAME}:production"
          else
            IMAGE_REF="${IMAGE_NAME}:v${VERSION}"
          fi

          echo "Using production image: $IMAGE_REF"
          echo "image-ref=$IMAGE_REF" >> $GITHUB_OUTPUT

      - name: Deploy to production
        run: |
          echo "Deploying to production with image: ${{ steps.image-info.outputs.image-ref }}"
          echo "Version: ${{ steps.version.outputs.version }}"

          # Deploy using the production image
          flyctl deploy \
            --image "${{ steps.image-info.outputs.image-ref }}" \
            --remote-only \
            --wait-timeout 600 \
            --verbose
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Verify production deployment
        run: |
          echo "Production deployment completed successfully!"
          echo "Production URL: https://test-battle.fly.dev"
          echo "Version: ${{ steps.version.outputs.version }}"

          # Wait for app to start
          sleep 60
          if curl -f https://test-battle.fly.dev/health > /dev/null 2>&1; then
            echo "✅ Production health check passed!"
          else
            echo "⚠️  Production health check failed, but deployment may still be starting up"
          fi
